### ISSUE TITLE
Fleet Model

### ISSUE THREAD

**Issue by Aw3someOne** [therealjimparry/comp4711-a1#4]
Fleet - the planes that make up your airline's fleet.
You will need a unique identifier for each airplane, and the kind of plane it is. Any other information is up to you.

view-source:http://wacky.jlparry.com/info/airplanes

We've decided on:
- Avanti
- Caravan

Your fleet can consist of any number and kind of recognized airplanes, subject to a budget limit of $10M. Your app will not be load-tested as part of assignment 1, and you can change your fleet for later assignments.

**Comment by Aw3someOne** [comment]
view-source:http://wacky.jlparry.com/info/airplanes
We've decided on 
Avanti
Caravan

**Comment by Aw3someOne** [comment]
Message: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0

**Comment by Aw3someOne** [comment]
Using curl instead of file_get_contents resolved the issue

**Comment by UnderratedDev** [comment]
fixed by using curl instead of file_get_contents which implicitly uses open
